return {
  "stevearc/conform.nvim",
  opts = {
    formatters_by_ft = {
      html = { "oxfmt" },
      css = { "oxfmt" },
      scss = { "oxfmt" },
      markdown = { "oxfmt" },
      javascript = { "oxfmt" },
      javascriptreact = { "oxfmt" },
      typescript = { "oxfmt" },
      typescriptreact = { "oxfmt" },
      yaml = { "oxfmt" },
      c = { "clang-format" },
      cpp = { "clang-format" },
      cmake = { "cmake_format" },
      python = { "ruff_format", "ruff_organize_imports" },
      sh = { "shfmt" },
      bash = { "shfmt" },
      zsh = { "shfmt" },
      nginx = { "nginxfmt" },
      nix = { "nixfmt" },
      dockerfile = { "dockerfmt", lsp_format = "fallback" },
      hcl = { "hcl" },
    },
  },
}
